from flask import Flask, render_template
import RPi.GPIO as GPIO
import time

PINS = {
    "c": 25,
    "c_sharp": 8,
    "d": 17,
    "d_sharp": 11,
    "e": 5,
    "f": 6,
    "f_sharp": 13,
    "g": 19,
    "g_sharp": 26,
    "a": 16,
    "a_sharp": 20,
    "b": 21
}

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
for pin in PINS.values():
    GPIO.setup(pin, GPIO.OUT)

app = Flask(__name__)


@app.route("/play_jingle_bells", methods=["POST"])
def play_jingle_bells():
     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(1)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)

     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(1)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)

     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["g"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["g"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["c"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["c"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["d"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["d"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(2)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)

     GPIO.output(PINS["f"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["f"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["f"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["f"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["f"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["f"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["f"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["f"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["f"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["f"], GPIO.LOW)
     time.sleep(0.5)

     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)

     GPIO.output(PINS["d"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["d"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["d"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["d"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.HIGH)
     time.sleep(0.5)
     GPIO.output(PINS["e"], GPIO.LOW)
     time.sleep(0.5)

     GPIO.output(PINS["d"], GPIO.HIGH)
     time.sleep(1)
     GPIO.output(PINS["d"], GPIO.LOW)
     time.sleep(0.5)
     GPIO.output(PINS["g"], GPIO.HIGH)
     time.sleep(1)
     GPIO.output(PINS["g"], GPIO.LOW)
     time.sleep(0.5)
     return "ok"


@app.route("/stop_jingle_bells", methods=["POST"])
def stop_jingle_bells():
    GPIO.output(PINS["c"], GPIO.LOW)
    return "ok"


@app.route("/play_happy_birthday", methods=["POST"])
def play_happy_birthday():
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["f"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["f"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["e"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["e"], GPIO.LOW)
    time.sleep(1)

    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["g"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["g"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["f"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["f"], GPIO.LOW)
    time.sleep(1)

    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["a"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["a"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["g"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["g"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["f"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["f"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["e"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["e"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.HIGH)
    time.sleep(2)
    GPIO.output(PINS["d"], GPIO.LOW)
    time.sleep(0.5)

    GPIO.output(PINS["g_sharp"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["g_sharp"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["g_sharp"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["g_sharp"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["g"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["g"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["d_sharp"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["d_sharp"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["f"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["f"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["d_sharp"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["d_sharp"], GPIO.LOW)
    time.sleep(0.5)
    return "ok"


@app.route("/stop_happpy_birthday", methods=["POST"])
def stop_happy_birthday():
    GPIO.output(PINS["c_sharp"], GPIO.LOW)
    return "ok"


@app.route("/play_hot_crossed_buns", methods=["POST"])
def play_hot_crossed_buns():
    GPIO.output(PINS["e"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["e"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["e"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["e"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)

    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.LOW)
    time.sleep(0.5)

    GPIO.output(PINS["d"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.LOW)
    time.sleep(0.5)

    GPIO.output(PINS["e"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["e"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.HIGH)
    time.sleep(0.5)
    GPIO.output(PINS["d"], GPIO.LOW)
    time.sleep(0.5)
    GPIO.output(PINS["c"], GPIO.HIGH)
    time.sleep(1)
    GPIO.output(PINS["c"], GPIO.LOW)
    return "ok"


@app.route("/stop_hot_crossed_buns", methods=["POST"])
def stop_hot_crossed_buns():
    GPIO.output(PINS["c_sharp"], GPIO.LOW)
    return "ok"


@app.route("/", methods=["GET"])
def home():
    return render_template("button.html", title="Button", name="Ashley Kulcsar")

